[window]
dimensions = { columns = 150, lines = 30 }
opacity = 0.9
startup_mode = "Windowed"

[scrolling]
history = 100
multiplier = 5

[font]
size = 10.0

[colors]
#primary.foreground = "#00f000" # default: #d8d8d8
cursor = { text = "#000000", cursor = "#d08000" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
