[window]
dimensions = { columns = 150, lines = 30 }
opacity = 0.975
startup_mode = "Windowed"

[scrolling]
multiplier = 5

[font]
size = 10.0

[colors]
cursor = { text = "#000000", cursor = "#d08000" }
normal.black = "#000000"
normal.red = "#a00050"
normal.green = "#00a000"
normal.yellow = "#fff070"
normal.blue = "#0070ff"
normal.magenta = "#e000c0"
normal.cyan = "#00e0ff"
normal.white = "#ffffff"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
